kind: Service
apiVersion: v1
metadata:
  labels:
    app: hello
  name: dep
  namespace: default
spec:
  selector:
    app: hello
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: NodePort
